class IceCreamRunner
{
	public static void main(String[] nuk)
	{
		IceCream icecream=new IceCream();
		IceCream icecream1=new IceCream();
		System.out.println(icecream1.flavor);
		IceCream icecream2=new IceCream();
		System.out.println(icecream2.flavor);
		System.out.println(icecream2.price);
		IceCream icecream3=new IceCream();
		System.out.println(icecream3.flavor);
		System.out.println(icecream3.price);
		System.out.println(icecream3.type);
		IceCream icecream4=new IceCream();
		System.out.println(icecream4.flavor);
		System.out.println(icecream4.price);
		System.out.println(icecream4.type);
		System.out.println(icecream4.brand);
		IceCream icecream5=new IceCream();
		System.out.println(icecream5.flavor);
		System.out.println(icecream5.price);
		System.out.println(icecream5.type);
		System.out.println(icecream5.brand);
		System.out.println(icecream5.weight);
		IceCream icecream6=new IceCream();
		System.out.println(icecream6.flavor);
		System.out.println(icecream6.price);
		System.out.println(icecream6.type);
		System.out.println(icecream6.brand);
		System.out.println(icecream6.weight);
		System.out.println(icecream6.quality);
		IceCream icecream7=new IceCream();
		System.out.println(icecream7.flavor);
		System.out.println(icecream7.price);
		System.out.println(icecream7.type);
		System.out.println(icecream7.brand);
		System.out.println(icecream7.weight);
		System.out.println(icecream7.quality);
        System.out.println(icecream7.quantity);
		IceCream icecream8=new IceCream();
		System.out.println(icecream8.flavor);
		System.out.println(icecream8.price);
		System.out.println(icecream8.type);
		System.out.println(icecream8.brand);
		System.out.println(icecream8.weight);
		System.out.println(icecream8.quality);
        System.out.println(icecream8.quantity);
		System.out.println(icecream8.dryFruit);
		IceCream icecream9=new IceCream();
		System.out.println(icecream9.flavor);
		System.out.println(icecream9.price);
		System.out.println(icecream9.type);
		System.out.println(icecream9.brand);
		System.out.println(icecream9.weight);
		System.out.println(icecream9.quality);
        System.out.println(icecream9.quantity);
		System.out.println(icecream9.dryFruit);
		System.out.println(icecream9.goodTaste);
		IceCream icecream10=new IceCream();
		System.out.println(icecream10.flavor);
		System.out.println(icecream10.price);
		System.out.println(icecream10.type);
		System.out.println(icecream10.brand);
		System.out.println(icecream10.weight);
		System.out.println(icecream10.quality);
        System.out.println(icecream10.quantity);
		System.out.println(icecream10.dryFruit);
		System.out.println(icecream10.goodTaste);
		System.out.println(icecream10.since);
	}
}
